// Package aria2 manages one resumable aria2c download at a time. The caller
// owns the cache directory and must retain it until the upload is verified.
package aria2

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/gofrs/flock"
	"pikpakvault/internal/update"
)

type Source struct {
	Binary   string
	Identity string
	Size     int64
	Open     func(context.Context, int64, int64) (io.ReadCloser, error)
}
type Progress struct{ Completed, Total, Speed int64 }
type ProgressFunc func(Progress) error
type runtimeState struct {
	PID, Port int
	Secret    string
}
type metadata struct {
	Identity string
	Size     int64
	Complete bool
}
type status struct {
	GID       string `json:"gid"`
	Status    string `json:"status"`
	Completed string `json:"completedLength"`
	Total     string `json:"totalLength"`
	Speed     string `json:"downloadSpeed"`
	Code      string `json:"errorCode"`
}

func nonce() string {
	b := make([]byte, 24)
	if _, e := rand.Read(b); e != nil {
		panic(e)
	}
	return hex.EncodeToString(b)
}
func readJSON(name string, v any) error {
	b, e := os.ReadFile(name)
	if e != nil {
		return e
	}
	return json.Unmarshal(b, v)
}
func writeJSON(name string, v any) error {
	b, e := json.Marshal(v)
	if e != nil {
		return e
	}
	return update.Atomic(name, b, 0600)
}

// All paths are fixed names under a cache directory generated by the caller.
// Refuse symlinks and unknown files rather than resuming or deleting elsewhere.
func Validate(dir string) error {
	info, e := os.Lstat(dir)
	if e != nil {
		return e
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("下载缓存目录无效")
	}
	entries, e := os.ReadDir(dir)
	if e != nil {
		return e
	}
	allowed := map[string]bool{"content": true, "content.aria2": true, "source.json": true, "runtime.json": true, "aria2.conf": true, "owner.json": true, "lock": true}
	for _, entry := range entries {
		if !allowed[entry.Name()] || entry.Type()&os.ModeSymlink != 0 || entry.IsDir() {
			return fmt.Errorf("下载缓存含无法确认的文件，已保留并停止处理")
		}
	}
	return nil
}

func (r runtimeState) rpc(method string, params []any, out any) error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	b, _ := json.Marshal(map[string]any{"jsonrpc": "2.0", "id": "vault", "method": "aria2." + method, "params": append([]any{"token:" + r.Secret}, params...)})
	req, e := http.NewRequestWithContext(ctx, "POST", fmt.Sprintf("http://127.0.0.1:%d/jsonrpc", r.Port), bytes.NewReader(b))
	if e != nil {
		return e
	}
	req.Header.Set("Content-Type", "application/json")
	c := http.Client{Transport: &http.Transport{Proxy: nil}}
	defer c.CloseIdleConnections()
	resp, e := c.Do(req)
	if e != nil {
		return fmt.Errorf("aria2 RPC 暂时不可用")
	}
	defer resp.Body.Close()
	var result struct {
		Result json.RawMessage `json:"result"`
		Error  json.RawMessage `json:"error"`
	}
	if e = json.NewDecoder(io.LimitReader(resp.Body, 1<<20)).Decode(&result); e != nil {
		return fmt.Errorf("aria2 RPC 响应无效")
	}
	if len(result.Error) > 0 {
		return fmt.Errorf("aria2 RPC %s 失败", method)
	}
	if out != nil {
		return json.Unmarshal(result.Result, out)
	}
	return nil
}

// A crash leaves a runtime record. Authenticate to that exact child and wait
// for its exit; never kill a PID that may now belong to another process.
func stopOrphan(dir string) error {
	var old runtimeState
	e := readJSON(filepath.Join(dir, "runtime.json"), &old)
	if errors.Is(e, os.ErrNotExist) {
		return nil
	}
	if e != nil {
		return fmt.Errorf("aria2 进程记录无效，已保留缓存")
	}
	if old.PID <= 0 || old.Port <= 0 || old.Port > 65535 || old.Secret == "" {
		return fmt.Errorf("aria2 进程记录不完整")
	}
	if !processAlive(old.PID) {
		return os.Remove(filepath.Join(dir, "runtime.json"))
	}
	_ = old.rpc("forcePauseAll", nil, nil)
	_ = old.rpc("shutdown", nil, nil)
	until := time.Now().Add(8 * time.Second)
	for time.Now().Before(until) {
		if !processAlive(old.PID) {
			return os.Remove(filepath.Join(dir, "runtime.json"))
		}
		time.Sleep(100 * time.Millisecond)
	}
	return fmt.Errorf("上次 aria2 进程尚未退出，已保留缓存；请稍后重试")
}

func Fetch(ctx context.Context, dir string, source Source, progress ProgressFunc) (string, error) {
	if source.Size < 0 || source.Identity == "" {
		return "", fmt.Errorf("下载来源记录无效")
	}
	if e := os.MkdirAll(dir, 0700); e != nil {
		return "", e
	}
	if e := Validate(dir); e != nil {
		return "", e
	}
	lock := flock.New(filepath.Join(dir, "lock"))
	ok, e := lock.TryLock()
	if e != nil {
		return "", e
	}
	if !ok {
		return "", fmt.Errorf("该文件的下载缓存正在使用")
	}
	defer lock.Unlock()
	if e = stopOrphan(dir); e != nil {
		return "", e
	}
	metaPath := filepath.Join(dir, "source.json")
	var meta metadata
	e = readJSON(metaPath, &meta)
	if e != nil && !errors.Is(e, os.ErrNotExist) {
		return "", e
	}
	if e == nil && (meta.Identity != source.Identity || meta.Size != source.Size) {
		return "", fmt.Errorf("下载缓存的来源已变化，请清理此任务的缓存后重试")
	}
	file := filepath.Join(dir, "content")
	if e != nil {
		if _, err := os.Stat(file); !errors.Is(err, os.ErrNotExist) {
			return "", fmt.Errorf("缓存缺少来源记录，已停止下载")
		}
		meta = metadata{Identity: source.Identity, Size: source.Size}
		if e = writeJSON(metaPath, meta); e != nil {
			return "", e
		}
	}
	var existing int64
	if info, err := os.Stat(file); err == nil {
		existing = info.Size()
		if !info.Mode().IsRegular() || existing > source.Size {
			return "", fmt.Errorf("缓存大小与来源不符")
		}
	}
	if meta.Complete {
		if _, err := os.Stat(file); err != nil {
			return "", fmt.Errorf("已完成的下载缓存文件缺失，请清理后重试")
		}
		if _, e = os.Stat(file + ".aria2"); !errors.Is(e, os.ErrNotExist) || existing != source.Size {
			return "", fmt.Errorf("已完成的下载缓存不完整，请清理后重试")
		}
		if e = progress(Progress{source.Size, source.Size, 0}); e != nil {
			return "", e
		}
		return file, nil
	}
	if source.Size == 0 {
		if e = os.WriteFile(file, nil, 0600); e != nil {
			return "", e
		}
		meta.Complete = true
		return file, writeJSON(metaPath, meta)
	}
	bin := source.Binary
	if bin == "" {
		return "", fmt.Errorf("专用 aria2 尚未准备完成")
	}
	available, e := freeSpace(dir)
	if e != nil {
		return "", e
	}
	needed := uint64(max(source.Size-existing, 0)) + (64 << 20)
	if available < needed {
		return "", fmt.Errorf("下载缓存空间不足：至少还需 %d MiB，可用 %d MiB；请清理缓存或扩容后重试", needed>>20, available>>20)
	}
	// aria2 talks only to a temporary loopback bridge. TelDrive credentials never
	// appear in argv, aria2 config/session files, logs, or redirected requests.
	listener, e := net.Listen("tcp4", "127.0.0.1:0")
	if e != nil {
		return "", e
	}
	bridgeCtx, cancelBridge := context.WithCancel(ctx)
	defer cancelBridge()
	var mu sync.Mutex
	lastError := ""
	secretPath := "/" + nonce()
	server := &http.Server{ReadHeaderTimeout: 10 * time.Second, Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != secretPath || (r.Method != "GET" && r.Method != "HEAD") {
			http.NotFound(w, r)
			return
		}
		start, end := int64(0), source.Size-1
		partial := r.Header.Get("Range") != ""
		if partial {
			v := strings.TrimPrefix(r.Header.Get("Range"), "bytes=")
			parts := strings.Split(v, "-")
			if len(parts) != 2 {
				w.WriteHeader(416)
				return
			}
			var err error
			start, err = strconv.ParseInt(parts[0], 10, 64)
			if err != nil {
				w.WriteHeader(416)
				return
			}
			if parts[1] != "" {
				end, err = strconv.ParseInt(parts[1], 10, 64)
				if err != nil {
					w.WriteHeader(416)
					return
				}
			}
			if start < 0 || start > end || end >= source.Size {
				w.WriteHeader(416)
				return
			}
		}
		w.Header().Set("Accept-Ranges", "bytes")
		w.Header().Set("Content-Type", "application/octet-stream")
		if r.Method == "HEAD" {
			w.Header().Set("Content-Length", strconv.FormatInt(source.Size, 10))
			return
		}
		requestCtx, stop := context.WithCancel(bridgeCtx)
		defer stop()
		stopClient := context.AfterFunc(r.Context(), stop)
		defer stopClient()
		reader, err := source.Open(requestCtx, start, end-start+1)
		if err != nil {
			mu.Lock()
			lastError = err.Error()
			mu.Unlock()
			http.Error(w, "source unavailable", 502)
			return
		}
		defer reader.Close()
		w.Header().Set("Content-Length", strconv.FormatInt(end-start+1, 10))
		if partial {
			w.Header().Set("Content-Range", fmt.Sprintf("bytes %d-%d/%d", start, end, source.Size))
			w.WriteHeader(206)
		}
		if _, err = io.CopyN(w, reader, end-start+1); err != nil {
			mu.Lock()
			lastError = "TelDrive 文件流提前断开，aria2 将按已保存进度续传"
			mu.Unlock()
		}
	})}
	go server.Serve(listener)
	defer server.Close()
	rpcListener, e := net.Listen("tcp4", "127.0.0.1:0")
	if e != nil {
		return "", e
	}
	runtime := runtimeState{Port: rpcListener.Addr().(*net.TCPAddr).Port, Secret: nonce()}
	rpcListener.Close()
	config := fmt.Sprintf("enable-rpc=true\nrpc-listen-all=false\nrpc-listen-port=%d\nrpc-secret=%s\n", runtime.Port, runtime.Secret)
	configPath := filepath.Join(dir, "aria2.conf")
	if e = update.Atomic(configPath, []byte(config), 0600); e != nil {
		return "", e
	}
	defer os.Remove(configPath)
	cmd := exec.Command(bin, "--conf-path="+configPath, "--no-conf=false", "--dir="+dir, "--out=content", "--continue=true", "--always-resume=true", "--auto-file-renaming=false", "--allow-overwrite=false", "--file-allocation=none", "--split=1", "--max-connection-per-server=1", "--max-concurrent-downloads=1", "--max-tries=8", "--retry-wait=3", "--connect-timeout=15", "--timeout=30", "--lowest-speed-limit=1K", "--auto-save-interval=1", "--check-integrity=true", "--disk-cache=0", "--enable-dht=false", "--enable-dht6=false", "--enable-peer-exchange=false", "--bt-enable-lpd=false", "--enable-color=false", "--summary-interval=0", "--console-log-level=error", "--download-result=hide", "--stop-with-process="+strconv.Itoa(os.Getpid()), "http://"+listener.Addr().String()+secretPath)
	configureProcess(cmd)
	// The bridge is loopback-only; inherited proxy settings must not forward it.
	for _, env := range os.Environ() {
		key := strings.ToLower(strings.SplitN(env, "=", 2)[0])
		if key != "http_proxy" && key != "https_proxy" && key != "all_proxy" {
			cmd.Env = append(cmd.Env, env)
		}
	}
	if e = cmd.Start(); e != nil {
		return "", fmt.Errorf("aria2 启动失败，请检查可执行文件与权限")
	}
	runtime.PID = cmd.Process.Pid
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	stopped := false
	stopChild := func() {
		if stopped {
			return
		}
		_ = runtime.rpc("forcePauseAll", nil, nil)
		_ = runtime.rpc("shutdown", nil, nil)
		select {
		case <-done:
			stopped = true
		case <-time.After(6 * time.Second):
			_ = cmd.Process.Kill()
			<-done
			stopped = true
		}
	}
	defer stopChild()
	if e = writeJSON(filepath.Join(dir, "runtime.json"), runtime); e != nil {
		return "", e
	}
	defer func() { stopChild(); _ = os.Remove(filepath.Join(dir, "runtime.json")) }()
	tick := time.NewTicker(300 * time.Millisecond)
	defer tick.Stop()
	started := time.Now()
	lastProgress := time.Time{}
	keys := []string{"gid", "status", "completedLength", "totalLength", "downloadSpeed", "errorCode"}
	for {
		select {
		case <-ctx.Done():
			return "", ctx.Err()
		case <-done:
			stopped = true
			return "", fmt.Errorf("aria2 进程提前退出，缓存已保留；请检查 aria2 安装后重试")
		case <-tick.C:
			var results []status
			e = runtime.rpc("tellActive", []any{keys}, &results)
			if e != nil {
				if time.Since(started) > 10*time.Second {
					return "", e
				}
				continue
			}
			if len(results) == 0 {
				e = runtime.rpc("tellStopped", []any{0, 10, keys}, &results)
				if e != nil {
					return "", e
				}
			}
			if len(results) == 0 {
				if time.Since(started) > 10*time.Second {
					return "", fmt.Errorf("aria2 未登记下载任务")
				}
				continue
			}
			s := results[0]
			completed, _ := strconv.ParseInt(s.Completed, 10, 64)
			total, _ := strconv.ParseInt(s.Total, 10, 64)
			speed, _ := strconv.ParseInt(s.Speed, 10, 64)
			if total != 0 && total != source.Size {
				return "", fmt.Errorf("aria2 下载长度与来源不符")
			}
			if time.Since(lastProgress) >= time.Second || s.Status == "complete" {
				if e = progress(Progress{completed, source.Size, speed}); e != nil {
					return "", e
				}
				lastProgress = time.Now()
			}
			if s.Status == "error" {
				mu.Lock()
				reason := lastError
				mu.Unlock()
				return "", fmt.Errorf("aria2 下载失败（错误码 %s），缓存已保留，请重试原任务。%s", s.Code, reason)
			}
			if s.Status == "complete" {
				stopChild()
				info, err := os.Stat(file)
				if err != nil {
					return "", err
				}
				if info.Size() != source.Size || completed != source.Size {
					return "", fmt.Errorf("aria2 完成结果大小不符")
				}
				if _, err = os.Stat(file + ".aria2"); !errors.Is(err, os.ErrNotExist) {
					return "", fmt.Errorf("aria2 仍有未完成的下载记录")
				}
				completedFile, err := os.OpenFile(file, os.O_RDWR, 0600)
				if err != nil {
					return "", err
				}
				err = completedFile.Sync()
				completedFile.Close()
				if err != nil {
					return "", err
				}
				meta.Complete = true
				if e = writeJSON(metaPath, meta); e != nil {
					return "", e
				}
				return file, nil
			}
		}
	}
}

// Remove only a known cache after its downloader has stopped. Failure retains
// both the partial file and .aria2 control file for subsequent resumption.
func Remove(dir string) error {
	if _, e := os.Stat(dir); errors.Is(e, os.ErrNotExist) {
		return nil
	}
	if e := Validate(dir); e != nil {
		return e
	}
	lock := flock.New(filepath.Join(dir, "lock"))
	ok, e := lock.TryLock()
	if e != nil {
		return e
	}
	if !ok {
		return fmt.Errorf("下载缓存仍在使用")
	}
	if e = stopOrphan(dir); e != nil {
		lock.Unlock()
		return e
	}
	// On Windows the open lock file cannot itself be removed.
	if e = lock.Unlock(); e != nil {
		return e
	}
	return os.RemoveAll(dir)
}
