import { useEffect, useState } from 'react'
import { NavLink, useLocation, useNavigate } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { motion } from 'motion/react'
import { toast } from 'sonner'
import { FolderClosed, Clock3, Star, Film, Image, Music2, FileText, ArrowDownToLine, Trash2, ShieldCheck, Settings2, UsersRound, Plus, Menu, ChevronsUpDown, ArrowUpRight, LockKeyhole, KeyRound, ArrowRight, Cloud, Sparkles, LogOut, Check, LoaderCircle, HardDrive } from 'lucide-react'
import { api, bytes, setCsrf } from './api'
import type { Account, Summary } from './api'
import { Logo, IconButton, Modal, Loading, ErrorState } from './components'
import FileBrowser from './FileBrowser'
import TelDrivePage from './TelDrive'
import { ImportDialog } from './dialogs'
import { BackupImport, ImportReviewBanner } from './Maintenance'
import { AccountsPage, TasksPage, RecoveryPage, SettingsPage } from './pages'

const navigation=[{path:'/files',label:'我的文件',icon:FolderClosed},{path:'/recent',label:'最近使用',icon:Clock3},{path:'/favorites',label:'我的收藏',icon:Star}]
const categories=[{path:'/video',label:'视频',icon:Film,color:'purple'},{path:'/image',label:'图片',icon:Image,color:'rose'},{path:'/audio',label:'音频',icon:Music2,color:'amber'},{path:'/documents',label:'文档与其他',icon:FileText,color:'blue'}]

export default function App(){
  const client=useQueryClient();const auth=useQuery({queryKey:['auth'],queryFn:()=>api<{configured:boolean;authenticated:boolean;csrf?:string}>('/auth/status'),retry:false});
  useEffect(()=>{if(auth.data?.csrf)setCsrf(auth.data.csrf)},[auth.data]);
  useEffect(()=>{const expire=()=>{setCsrf('');client.setQueryData(['auth'],{configured:true,authenticated:false});client.removeQueries({predicate:q=>q.queryKey[0]!=='auth'})};window.addEventListener('vault:unauthorized',expire);return()=>window.removeEventListener('vault:unauthorized',expire)},[client]);
  if(auth.isLoading)return <div className="boot"><Logo/><Loading/></div>;
  if(auth.error)return <div className="boot"><Logo/><ErrorState error={auth.error} retry={()=>auth.refetch()}/></div>;
  if(!auth.data?.authenticated)return <Login configured={!!auth.data?.configured} onLogin={()=>auth.refetch()}/>;
  return <Workspace/>;
}
function Login({configured,onLogin}:{configured:boolean;onLogin:()=>void}){
  const [password,setPassword]=useState('');const [token,setToken]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const v=await api<{csrf:string}>(configured?'/auth/login':'/auth/setup',configured?{password}:{password,token});setCsrf(v.csrf);onLogin()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="login-page"><div className="login-top"><Logo/><span className="private-label"><LockKeyhole size={13}/> PRIVATE CLOUD, YOURS TO KEEP</span></div><main className="login-main"><section className="login-intro"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.6}}><span className="eyebrow">A HOME FOR YOUR FINDS</span><h1>好内容，<br/>值得<span>一直收藏。</span></h1><p>把发现的世界，放进自己的云端。<br/>保存、整理、重拾，每一份热爱都有迹可循。</p></motion.div><div className="login-collection"><motion.div className="sample-card sample-video" animate={{y:[0,-8,0],rotate:[-7,-5,-7]}} transition={{repeat:Infinity,duration:7,ease:'easeInOut'}}><div className="sample-orbit"><Film size={35}/></div><small>THE COLLECTION</small><strong>Every story.<br/>Safely kept.</strong><span>你的电影收藏夹 <ArrowUpRight size={13}/></span></motion.div><motion.div className="sample-card sample-folder" animate={{y:[0,9,0]}} transition={{repeat:Infinity,duration:6,ease:'easeInOut'}}><FolderClosed size={40} fill="currentColor"/><strong>灵感永不散场</strong><span>想留住的，都在这里</span></motion.div><motion.div className="floating-check" animate={{y:[0,-6,0]}} transition={{repeat:Infinity,duration:5}}><ShieldCheck size={21}/><span>来源已备份</span><Check size={15}/></motion.div><span className="decor-dot dot-1"/><span className="decor-dot dot-2"/></div></section><section className="login-panel"><span className="login-lock"><LockKeyhole size={23}/></span><h2>{configured?'欢迎回到你的资源库':'开启你的私人资源库'}</h2><p>{configured?'登录后，继续收藏你喜欢的世界。':'先为这个空间设置一个管理员密码。'}</p><form onSubmit={submit}>{!configured&&<label>初始化代码<div className="input-icon"><KeyRound size={17}/><input value={token} onChange={e=>setToken(e.target.value)} required autoComplete="off" placeholder="在服务器启动日志中查看"/></div></label>}<label>{configured?'访问密码':'设置访问密码'}<div className="input-icon"><LockKeyhole size={17}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={configured?undefined:10} maxLength={256} required autoComplete={configured?'current-password':'new-password'} placeholder={configured?'输入你的管理员密码':'至少 10 位字符'}/></div></label>{error&&<div className="inline-error" role="alert">{error}</div>}<button className="button primary login-submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<>{configured?'进入资源库':'创建我的空间'}<ArrowRight size={18}/></>}</button></form>{!configured&&<><div className="setup-import-divider">已有资源库</div><BackupImport setup onImported={onLogin}/></>}<div className="login-security"><ShieldCheck size={15}/><span>独立访问 · 账号凭据加密存储</span></div></section></main><footer className="login-footer"><span>PikPak Vault</span><span>A little space for everything you love.</span></footer></div>
}
function Workspace(){
  const client=useQueryClient();const location=useLocation();const navigate=useNavigate();const [menu,setMenu]=useState(false);const [importOpen,setImportOpen]=useState(false);const [importParent,setImportParent]=useState('root');
  const accounts=useQuery({queryKey:['accounts'],queryFn:()=>api<{accounts:Account[];active_id:string}>('/accounts')});
  const summary=useQuery({queryKey:['summary'],queryFn:()=>api<Summary>('/summary')});
  const active=accounts.data?.accounts.find(a=>a.id===accounts.data?.active_id);
  useEffect(()=>{const events=new EventSource('/api/v1/events');let timer:ReturnType<typeof setTimeout>|undefined;events.addEventListener('change',()=>{clearTimeout(timer);timer=setTimeout(()=>{client.invalidateQueries({predicate:q=>q.queryKey[0]!=='auth'&&q.queryKey[0]!=='media'&&q.queryKey[0]!=='preview'})},200)});events.addEventListener('unauthorized',()=>window.dispatchEvent(new Event('vault:unauthorized')));events.onerror=()=>{client.invalidateQueries({queryKey:['summary']})};return()=>{clearTimeout(timer);events.close()}},[client]);
  useEffect(()=>{setMenu(false)},[location.pathname]);
  function openImport(parent=new URLSearchParams(location.search).get('folder')||'root'){if(!active){navigate('/accounts');toast.info('先连接一个 PikPak 账号');return}setImportParent(parent);setImportOpen(true)}
  async function logout(){try{await api('/auth/logout',{});setCsrf('');client.clear();client.setQueryData(['auth'],{configured:true,authenticated:false})}catch(e){toast.error((e as Error).message)}}
  const sidebar=<><div className="sidebar-brand"><Logo/></div><button className="button primary add-resource" onClick={()=>openImport()}><Plus size={19}/> 添加资源</button><nav aria-label="主导航"><div className="nav-group">{navigation.map(({path,label,icon:Icon})=><NavLink key={path} to={path}><Icon size={19}/><span>{label}</span>{path==='/files'&&!!summary.data?.count&&<small>{summary.data.count}</small>}</NavLink>)}</div><div className="nav-caption">按类型浏览</div><div className="nav-group types">{categories.map(({path,label,icon:Icon,color})=><NavLink key={path} to={path}><Icon size={18} className={color}/><span>{label}</span></NavLink>)}</div><div className="nav-divider"/><div className="nav-group"><NavLink to="/tasks"><ArrowDownToLine size={19}/><span>传输任务</span>{!!summary.data?.tasks&&<small className="nav-count">{summary.data.tasks}</small>}</NavLink><NavLink to="/teldrive"><Cloud size={18}/><span>TelDrive 同步</span></NavLink><NavLink to="/trash"><Trash2 size={18}/><span>回收站</span></NavLink></div></nav><div className="sidebar-bottom"><NavLink to="/recovery" className="recovery-nav"><span className="recovery-icon"><ShieldCheck size={20}/></span><span><strong>恢复中心</strong><small>{summary.data?.missing?`${summary.data.missing} 项资源待检查`:'为你的收藏，多留一份底气'}</small></span><ArrowUpRight size={15}/>{!!summary.data?.missing&&<i/>}</NavLink><div className="storage-card"><div><span><Cloud size={15}/>云端空间</span><button aria-label="管理账号" onClick={()=>navigate('/accounts')}><ArrowUpRight size={15}/></button></div><div className="storage-meter"><i style={{width:`${active?.quota_limit?Math.min(active.quota_used/active.quota_limit*100,100):0}%`}}/></div><p>{active?.quota_limit?<><strong>{bytes(active.quota_used)}</strong> / {bytes(active.quota_limit)}</>:active?'正在获取账号容量':'连接账号，开启收藏'}</p></div><div className="sidebar-foot"><NavLink to="/accounts" aria-label="账号管理"><UsersRound size={18}/><span>账号</span></NavLink><NavLink to="/settings" aria-label="设置"><Settings2 size={18}/><span>设置</span></NavLink><IconButton label="退出登录" onClick={logout}><LogOut size={17}/></IconButton></div></div></>;
  const path=location.pathname;const view=path.split('/')[1]||'files';
  const isFileView=!['accounts','tasks','recovery','settings','teldrive'].includes(view);
  const navigationControl=<IconButton label="打开导航" className="mobile-menu" onClick={()=>setMenu(true)}><Menu size={21}/></IconButton>;
  const accountControl=<button className="account-switch" aria-label={`管理账号：${active?.name||'连接账号'}`} title={active?.name||'连接账号'} onClick={()=>navigate('/accounts')}><span className="avatar">{(active?.name||'V').slice(0,1).toUpperCase()}</span><span className="account-name">{active?.name||'连接账号'}</span><ChevronsUpDown size={14}/></button>;
  return <div className="app-shell"><aside className="sidebar">{sidebar}</aside><Modal open={menu} onClose={()=>setMenu(false)} title="我的空间" className="mobile-nav-modal"><div className="mobile-sidebar">{sidebar}</div></Modal><main className="main-shell"><ImportReviewBanner/>{!isFileView&&<header className="topbar"><div className="topbar-left"><IconButton label="打开导航" className="mobile-menu" onClick={()=>setMenu(true)}><Menu size={21}/></IconButton><span className="workspace-name"><span className="workspace-dot"/>个人资源库 <span className="personal-tag">PRIVATE</span></span></div><div className="topbar-right"><span className="topbar-saved"><ShieldCheck size={15}/>本地来源备份</span><button className="account-switch" onClick={()=>navigate('/accounts')}><span className="avatar">{(active?.name||'V').slice(0,1).toUpperCase()}</span><span>{active?.name||'连接账号'}</span><ChevronsUpDown size={14}/></button></div></header>}<div className="page-area">{view==='teldrive'?<TelDrivePage/>:view==='accounts'?<AccountsPage/>:view==='tasks'?<TasksPage/>:view==='recovery'?<RecoveryPage/>:view==='settings'?<SettingsPage/>:<FileBrowser key={view} view={view} onImport={openImport} navigationControl={navigationControl} accountControl={accountControl}/>}</div></main><ImportDialog open={importOpen} parent={importParent} onClose={()=>setImportOpen(false)}/></div>
}
